default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: schedulent_development

test:
  <<: *default
  database: schedulent_test

production:
  <<: *default
  database: schedulent_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV['SCHEDULENT_DATABASE_PASSWORD'] %>
